// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiCantina.Data.Context;

#nullable disable

namespace WebApiCantina.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250516210252_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApiCantina.Domain.Models.Estoque.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<DateOnly>("DataCriacao")
                        .HasColumnType("date");

                    b.Property<string>("DescricaoCategoria")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ImagemCategoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("WebApiCantina.Domain.Models.Estoque.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProduto"));

                    b.Property<int?>("CarrinhoIdCarrinho")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DataCriacao")
                        .HasColumnType("date");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("PrecoCusto")
                        .HasColumnType("double");

                    b.Property<double>("PrecoVenda")
                        .HasColumnType("double");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("int");

                    b.HasKey("IdProduto");

                    b.HasIndex("CarrinhoIdCarrinho");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("WebApiCantina.Domain.Models.Operacoes.Carrinho", b =>
                {
                    b.Property<int>("IdCarrinho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCarrinho"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ClienteIdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("VendedorIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdCarrinho");

                    b.HasIndex("ClienteIdUsuario");

                    b.HasIndex("VendedorIdUsuario");

                    b.ToTable("Comandas");
                });

            modelBuilder.Entity("WebApiCantina.Domain.Models.Usuarios.Administrador", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("CodigoAdministrador")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<DateOnly>("DataCriacao")
                        .HasColumnType("date");

                    b.Property<string>("NomeAdministrador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.ToTable("administradores");
                });

            modelBuilder.Entity("WebApiCantina.Domain.Models.Usuarios.Colaborador", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("CodigoColaborador")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<DateOnly>("DataCriacao")
                        .HasColumnType("date");

                    b.Property<string>("NomeColaborador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.ToTable("colaboradores");
                });

            modelBuilder.Entity("WebApiCantina.Domain.Models.Usuarios.Comum", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateOnly>("DataCriacao")
                        .HasColumnType("date");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.ToTable("comuns");
                });

            modelBuilder.Entity("WebApiCantina.Domain.Models.Estoque.Produto", b =>
                {
                    b.HasOne("WebApiCantina.Domain.Models.Operacoes.Carrinho", null)
                        .WithMany("Produtos")
                        .HasForeignKey("CarrinhoIdCarrinho");

                    b.HasOne("WebApiCantina.Domain.Models.Estoque.Categoria", "CategoriaProduto")
                        .WithMany("Produtos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaProduto");
                });

            modelBuilder.Entity("WebApiCantina.Domain.Models.Operacoes.Carrinho", b =>
                {
                    b.HasOne("WebApiCantina.Domain.Models.Usuarios.Comum", "Cliente")
                        .WithMany("Carrinhos")
                        .HasForeignKey("ClienteIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiCantina.Domain.Models.Usuarios.Colaborador", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WebApiCantina.Domain.VOs.Preco", "ValorTotal", b1 =>
                        {
                            b1.Property<int>("CarrinhoIdCarrinho")
                                .HasColumnType("int");

                            b1.Property<double>("Valor")
                                .HasColumnType("double");

                            b1.HasKey("CarrinhoIdCarrinho");

                            b1.ToTable("Comandas");

                            b1.WithOwner()
                                .HasForeignKey("CarrinhoIdCarrinho");
                        });

                    b.Navigation("Cliente");

                    b.Navigation("ValorTotal")
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("WebApiCantina.Domain.Models.Usuarios.Administrador", b =>
                {
                    b.OwnsOne("WebApiCantina.Domain.VOs.Cpf", "CpfUsuario", b1 =>
                        {
                            b1.Property<int>("AdministradorIdUsuario")
                                .HasColumnType("int");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("AdministradorIdUsuario");

                            b1.ToTable("administradores");

                            b1.WithOwner()
                                .HasForeignKey("AdministradorIdUsuario");
                        });

                    b.OwnsOne("WebApiCantina.Domain.VOs.Email", "Email", b1 =>
                        {
                            b1.Property<int>("AdministradorIdUsuario")
                                .HasColumnType("int");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("AdministradorIdUsuario");

                            b1.ToTable("administradores");

                            b1.WithOwner()
                                .HasForeignKey("AdministradorIdUsuario");
                        });

                    b.OwnsOne("WebApiCantina.Domain.VOs.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<int>("AdministradorIdUsuario")
                                .HasColumnType("int");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("AdministradorIdUsuario");

                            b1.ToTable("administradores");

                            b1.WithOwner()
                                .HasForeignKey("AdministradorIdUsuario");
                        });

                    b.Navigation("CpfUsuario")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Telefone")
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiCantina.Domain.Models.Usuarios.Colaborador", b =>
                {
                    b.OwnsOne("WebApiCantina.Domain.VOs.Cpf", "CpfUsuario", b1 =>
                        {
                            b1.Property<int>("ColaboradorIdUsuario")
                                .HasColumnType("int");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("ColaboradorIdUsuario");

                            b1.ToTable("colaboradores");

                            b1.WithOwner()
                                .HasForeignKey("ColaboradorIdUsuario");
                        });

                    b.OwnsOne("WebApiCantina.Domain.VOs.Email", "Email", b1 =>
                        {
                            b1.Property<int>("ColaboradorIdUsuario")
                                .HasColumnType("int");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("ColaboradorIdUsuario");

                            b1.ToTable("colaboradores");

                            b1.WithOwner()
                                .HasForeignKey("ColaboradorIdUsuario");
                        });

                    b.OwnsOne("WebApiCantina.Domain.VOs.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<int>("ColaboradorIdUsuario")
                                .HasColumnType("int");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("ColaboradorIdUsuario");

                            b1.ToTable("colaboradores");

                            b1.WithOwner()
                                .HasForeignKey("ColaboradorIdUsuario");
                        });

                    b.Navigation("CpfUsuario")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Telefone")
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiCantina.Domain.Models.Usuarios.Comum", b =>
                {
                    b.OwnsOne("WebApiCantina.Domain.VOs.Cpf", "CpfUsuario", b1 =>
                        {
                            b1.Property<int>("ComumIdUsuario")
                                .HasColumnType("int");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("ComumIdUsuario");

                            b1.ToTable("comuns");

                            b1.WithOwner()
                                .HasForeignKey("ComumIdUsuario");
                        });

                    b.OwnsOne("WebApiCantina.Domain.VOs.Email", "Email", b1 =>
                        {
                            b1.Property<int>("ComumIdUsuario")
                                .HasColumnType("int");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("ComumIdUsuario");

                            b1.ToTable("comuns");

                            b1.WithOwner()
                                .HasForeignKey("ComumIdUsuario");
                        });

                    b.OwnsOne("WebApiCantina.Domain.VOs.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<int>("ComumIdUsuario")
                                .HasColumnType("int");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("ComumIdUsuario");

                            b1.ToTable("comuns");

                            b1.WithOwner()
                                .HasForeignKey("ComumIdUsuario");
                        });

                    b.Navigation("CpfUsuario")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Telefone")
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiCantina.Domain.Models.Estoque.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("WebApiCantina.Domain.Models.Operacoes.Carrinho", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("WebApiCantina.Domain.Models.Usuarios.Comum", b =>
                {
                    b.Navigation("Carrinhos");
                });
#pragma warning restore 612, 618
        }
    }
}
